[workspace]
resolver = "2"
members = ["xtask", "crates/*"]

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.0.1"

[workspace.dependencies]
anyhow = "1.0.100"
xshell = "0.2.7"
rustdoc-md = "0.2.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
rustdoc-types = "0.56.0"
jiff = "0.2.18"
